### ISSUE TITLE
There are no code examples in the docs

### ISSUE THREAD

**Issue by ubershmekel** [harlowja/fasteners#11]
Am I looking in the wrong place?

**Comment by harlowja** [comment]
We could use some, if you want to submit a PR, feel free :)

**Comment by ubershmekel** [comment]
Cool. I'll be trying this module out next week. I'll try and report back soon.

**Comment by harlowja** [comment]
Sounds great.

**Comment by noobermin** [comment]
*cough* many of us would appreciate something like this.

**Comment by ubershmekel** [comment]
https://github.com/harlowja/fasteners/pull/14

**Comment by harlowja** [comment]
u should get checked out for a cold noobermin ;)

**Comment by harlowja** [comment]
Your wish is my command :stuck_out_tongue:

**Comment by harlowja** [comment]
https://fasteners.readthedocs.org/en/latest/examples.html

**Comment by harlowja** [comment]
Enjoy!
