### ISSUE TITLE
[0.19] Are We Droping Python <= 3.7 Support?

### ISSUE THREAD

**Issue by hswong3i** [harlowja/fasteners#110]
From 0.19 release note (https://github.com/harlowja/fasteners/releases/tag/0.19), we mentioned:

- Adds non-context manager methods to inter-thread lock
- Drops support for python 3.7
- Adds CI for python 3.11

BTW:

- From https://pypi.org/project/fasteners/0.19, we could see the "Requires: Python >=3.6".
- From https://github.com/harlowja/fasteners/blob/0.19/setup.cfg, we could also see the "python_requires = >=3.6"

Now when I checking with `pip list --outdated` on CentOS 7, it show as below:
```
Package        Version Latest  Type
-------------- ------- ------- -----
fasteners      0.18    0.19    wheel
```

@psarka maybe we need a fix for it?

**Comment by psarka** [comment]
Thank you, I missed those!

It still works on python 3.7, so no harm done, but I'll take a note to update the `python_requires` section.

**Comment by hswong3i** [comment]
@psarka thank you for clarify ;-)
