### ISSUE TITLE
Refactor: pick first not none

### ISSUE THREAD

**Issue by buhtz** [harlowja/fasteners#117]
Hello,

just stumbled over that code.

https://github.com/harlowja/fasteners/blob/06c3f06cab4e135b8d921932019a231c180eb9f4/fasteners/_utils.py#L42-L48

This would be faster than a usual for loop. It use `filter()` to exclude `None` values from the list and then pick the first entry from that list.

    try:
        return list(filter(lambda val: val is not None, values))[0]
    except IndexError:
        return None

**Comment by psarka** [comment]
Thanks for the issue!

I'm a bit confused, as this function is barely used. What was your usage scenario?

**Comment by buhtz** [comment]
Hello Paulius,
I wasn't using it. I was just looking into your code to see how do you solve the flock problem. I thought about using your package for [backintime](https://github.com/bit-team/backintime). But in the end I decided to implement something myself because we don't need that much features and it is currently also not clear what we really need. Our project is 15 year old smelly code we took over 3 years ago. And now we are refactoring it.

**Comment by psarka** [comment]
Got it!

In that case I'll leave that code be, as it can't realistically have a performance impact :)
