### ISSUE TITLE
Allow `InterProcessLock` to receive a `pathlib.Path` object

### ISSUE THREAD

**Issue by cool-RR** [harlowja/fasteners#16]

**Comment by harlowja** [comment]
Sounds good to me as long as it will work on both py2.7 and py3.x

**Comment by cool-RR** [comment]
I think it will since you don't even need the package, just call str(path)
on the paths and you're done. You need pathlib just for the tests, and
there is a python 2 backport.

**Comment by harlowja** [comment]
Agreed, although probably better to call https://docs.python.org/3/library/os.html#os.fsencode if we can...

**Comment by harlowja** [comment]
Ok checkout https://github.com/harlowja/fasteners/pull/17 (I'll add some tests but seems to work locally).

**Comment by cool-RR** [comment]
Be wary of `isinstance(path, pathlib.Path)`, because some people, like me,
bundle `pathlib` in another package so this check would fail for them. I
would skip the pathlib import completely, even though it's in `try`. You
can basically check if it's a string, and if it's not turn it into a string
in your favorite way.

**Comment by harlowja** [comment]
Hmmm, why u bundling it :frowning: 

I get that concern, but it seems like a 1% case (and not especially a 1% case that I like, bundling stuff IMHO is ummm not helping the python ecosystem in general, although I get the reasons why people do it, I just don't agree with them, ha).

**Comment by cool-RR** [comment]
Also consider there are alternatives to Pathlib which act similarly but
will still fail your test. You can't isinstance all of them but you can do
str(path) which will work for all of them, I think.

**Comment by harlowja** [comment]
Fair enough, maybe should just do str() as u said...
