### ISSUE TITLE
Use Appveyor to make sure things keep working on Windows

### ISSUE THREAD

**Issue by johntyree** [harlowja/fasteners#24]
It would be great to get Windows-based tests running regularly. It's free for OSS.

www.appveyor.com

As the repo owner, I think you, @harlowja, or a blessed contributor need to actually set it up.

**Comment by harlowja** [comment]
Yup, I'll work on getting this setup when I get back from my break (end of week).

**Comment by harlowja** [comment]
Ok, https://ci.appveyor.com/project/JoshuaHarlow/fasteners let's see if this works, ha

**Comment by johntyree** [comment]
:dancer: :tada:
