### ISSUE TITLE
conda-forge maintainers

### ISSUE THREAD

**Issue by alimanfoo** [harlowja/fasteners#25]
Hi @harlowja, I am using fasteners in another package ([Zarr](http://zarr.readthedocs.io/en/latest/)), many thanks for developing it. I recently added Zarr to [conda-forge](http://conda-forge.github.io) to simplify installation for people using conda, and as part of making that possible I also needed to add fasteners to conda-forge. I've created a [feedstock for the fasteners package](https://github.com/conda-forge/fasteners-feedstock) and would be very happy to add you as a maintainer, which would mean that you could keep the recipe up to date with any new fasteners releases. Just let me know if you'd like me to add you as a maintainer, and/or anyone else. Thanks again.

**Comment by harlowja** [comment]
If you have interest in maintaining the conda-forge files go for it; I don't think I'd be the right maintainer.
