### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by catb0t** [harlowja/fasteners#28]
I was looking into the tests folder to try to find a code example I could work from, but it left me as baffled as [the documentation](https://fasteners.readthedocs.io/en/latest/api/lock.html#classes).

Excerpted from 
[class ReadWriteLockTest in test_lock.py](https://github.com/harlowja/fasteners/blob/master/fasteners/tests/test_lock.py#L102):

```python
def test_no_double_writers(self):
        lock = fasteners.ReaderWriterLock()   # a lock on what exactly? no filename is given
        watch = _utils.StopWatch(duration=5)
        watch.start()
        dups = collections.deque()
        active = collections.deque()

        def acquire_check(me):
            with lock.write_lock():    # what does this with statement lock?
```

Neither in the documentation nor in the testing code is it very clear, how to use this `ReaderWriterLock` to lock access to a resource? A filename, nor any sort of context is ever given to these functions.

**Comment by harlowja** [comment]
A reader-writer lock is https://en.wikipedia.org/wiki/Readers%E2%80%93writer_lock

**Comment by philippludwig** [comment]
Same here. Nice that there is an article available about the theory behind it, but that still does not explain how this library is intended to be used.

**Comment by psarka** [comment]
I'll note that the README was rewritten with this question in mind, but I will keep this issue open until the documentation is improved as well.

**Comment by psarka** [comment]
Documentation is now pretty good :tada:
