### ISSUE TITLE
Please make the code compatible with Python3.8

### ISSUE THREAD

**Issue by MeggyCal** [harlowja/fasteners#38]
I mean:
/usr/lib/python3.7/site-packages/unittest2/compatibility.py:143
  /usr/lib/python3.7/site-packages/unittest2/compatibility.py:143: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    class ChainMap(collections.MutableMapping):

Thank you very much :) .

**Comment by psarka** [comment]
Something got mixed up here, we do not import any ABCs from anywhere, and the code runs fine on python 3.8. I'll close this then, please reopen if I'm mistaken.
