### ISSUE TITLE
A brief plan

### ISSUE THREAD

**Issue by psarka** [harlowja/fasteners#52]
@harlowja 

Before I start changing things, I thought I'd share my intentions, to see if that's ok with you.

1. I'd like to start with merging my own PR #50, as it is written to support python 2.7. It would be nice if someone could review it, but if no one has time, I am willing to merge it as is. After this we could release the last version that supports 2.7.

2. Then I'd like to migrate the code to python 3.6+, removing python 2.7 legacy and making sure fasteners work with newer versions such as 3.8 & 3.9  (issue #38)

3. Then I'd like to start resolving all the outstanding issues and PR's, starting with documentation (easiest), and ending with offset locks (hardest).

Let me know what you think, also, please let me know if there are more active maintainers of fasteners, and if I should pay attention to some other projects that fasteners seem to be related (openstack?)

**Comment by harlowja** [comment]
Will get back to this later tonight (got me real job to look after).

**Comment by psarka** [comment]
Bump :)

**Comment by harlowja** [comment]
Ah, overall looks fine to me. I think openstack should be fine with these changes; as long as the core API doesn't break. Though I'll have to ask some people if 2.7 support can be dropped entirely (I think it can, just need to verify).
