### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by manoprenko** [harlowja/fasteners#61]
Hi!

It would be great to make a new release (particularly I'm interested in [this commit](https://github.com/harlowja/fasteners/commit/be8f96ef28e8247546de62befc9c08336074adeb)) and to have it available on pypi. Could you help with this?

**Comment by psarka** [comment]
@harlowja I think this is a good point to make a release.

It has accumulated a couple of features and fixes, and would be the last for python 2.7, what do you think?

I can make the update to the changelog, is there anything else I can do to help you with this?

**Comment by harlowja** [comment]
Sounds good to me, let's do it. I can try to get that done after you update the changelog; shouldn't be hard :-P

**Comment by psarka** [comment]
Voila: https://github.com/harlowja/fasteners/pull/62

**Comment by psarka** [comment]
@harlowja Check out the github actions, there is a default one for publishing to pypi, maybe you will find it worthwhile to setup :)
https://github.com/harlowja/fasteners/actions/new

**Comment by harlowja** [comment]
Probably a good idea, since I don't have tons of time to do all this stuff, lol

**Comment by psarka** [comment]
I added the required action to master, all it remains is for you to go to repo Settings -> Secrets and add two env variables:

PYPI_USERNAME
PYPI_PASSWORD

When that's done, create a new release v0.16, and it will be uploaded to PyPi automatically.

**Comment by harlowja** [comment]
How about I add you as co-maintainer on pypi :-P

**Comment by harlowja** [comment]
What's your PYPI username?

**Comment by psarka** [comment]
That would work as well, my PYPI username is the same - psarka.

But in this case you will need to give me admin rights to this repository, as I can't access the settings at the moment.

**Comment by harlowja** [comment]
Ok, u got invited on pypi, but doesn't seem that github has a way to give you admin rights to this repository from what I can tell, may just have to upload to pypi via other methods for now.

**Comment by harlowja** [comment]
I'll see about doing that settings setup at some point in the future, I guess for now just upload manually with `twine` `upload` 

https://twine.readthedocs.io/en/latest/#twine-upload

**Comment by psarka** [comment]
Done!

https://pypi.org/project/fasteners/0.16/

**Comment by harlowja** [comment]
Awesome, nice.

**Comment by manoprenko** [comment]
Thanks a lot guys!
