### ISSUE TITLE
Admin chores

### ISSUE THREAD

**Issue by psarka** [harlowja/fasteners#90]
@harlowja I have two tasks for you, as an admin of this repo. Could you, please:

1. Switch the default branch from `master` to `main` (Settings -> Branches).
2. Fix or install the webhook for readthedocs, so that it updates the docs at every push to `main`.

Thanks :)

**Comment by psarka** [comment]
@harlowja ping! :)

**Comment by psarka** [comment]
@harlowja I would like to see this happen, could you indicate that you at least see the messages? If you are too busy to deal with readthedocs, alternative would be to take down readthedocs page altogether, and I would replace it with github pages.

**Comment by harlowja** [comment]
Hi there,

I'll try to get some of this done over the weekend,

Sorry about being slow :-P

**Comment by psarka** [comment]
@harlowja A kind reminder that the chores still await you! :)

Let me help you a bit:

Switch the branch (~30sec)
1. Click the ⚙ Settings on the top of this page
2. Choose Branches on the left
3. Choose `main` as default

Add me to read the docs maintainers (~1min, unless you lost the password, then ~2min.)
1. Login to read the docs
2. Click fasteners project
3. Click ⚙ Admin
4. Click Maintainers on the left
5. Add `psarka` as a maintainer

**Comment by harlowja** [comment]
I'm on it, haha

**Comment by harlowja** [comment]
Default branch updated to "main"

Added you as admin/maintainer on readthedocs.

Sorry about taking so long, started a new job @ Waymo a few months ago and have
been busy trying to come up to speed there.

**Comment by psarka** [comment]
Behold! Updated documentation! 

https://fasteners.readthedocs.io/en/latest/

Thanks @harlowja :)

**Comment by harlowja** [comment]
Much appreciated; sorry for being slow, lol.
