### ISSUE TITLE
Bad link in the docs.

### ISSUE THREAD

**Issue by Erotemic** [harlowja/fasteners#95]
On the page: https://fasteners.readthedocs.io/en/latest/

The "Reference" link to https://fasteners.readthedocs.io/en/latest/reference.index.md 

links to a odd page that seems broken: 

![image](https://user-images.githubusercontent.com/3186211/185223542-89ddcf4c-47ec-42c8-8bd3-f1d293dd57d8.png)

**Comment by psarka** [comment]
Fixed! Thanks @Erotemic :+1:
